import { defineConfig } from 'tsup';

export default defineConfig({
    entry: {
        index: 'src/index.ts',
        core: 'src/core/index.ts',
        memory: 'src/memory/index.ts',
        tools: 'src/tools/index.ts',
        planner: 'src/planner/index.ts',
        execution: 'src/execution/index.ts',
        orchestration: 'src/orchestration/index.ts',
        observability: 'src/observability/index.ts',
        llm: 'src/llm/index.ts',
        agentic: 'src/agentic/index.ts',
        session: 'src/session/index.ts',
        guardrails: 'src/guardrails/index.ts',
        knowledge: 'src/knowledge/index.ts',
        storage: 'src/storage/index.ts',
        production: 'src/production/index.ts',
        artifacts: 'src/artifacts/index.ts',
        voice: 'src/voice/index.ts',
        runtime: 'src/runtime/index.ts',
        /** Subpath `confused-ai/create-agent` — lean entry without pulling the full umbrella bundle */
        'create-agent': 'src/create-agent.ts',
        cli: 'src/cli/index.ts',
        'tools/shell': 'src/tools/shell-entry.ts',
        contracts: 'src/contracts/index.ts',
        plugins: 'src/plugins/index.ts',
        adapters: 'src/adapters/index.ts',
        background: 'src/background/index.ts',
        testing: 'src/testing/index.ts',
        learning: 'src/learning/index.ts',
        video: 'src/video/index.ts',
        config: 'src/config/index.ts',
    },
    format: ['cjs', 'esm'],
    dts: true,
    splitting: false,
    sourcemap: true,
    clean: true,
    treeshake: true,
    /** Lazy `require()` — install only what you use; must not be resolved at bundle time */
    external: [
        '@anthropic-ai/sdk',
        '@google/generative-ai',
        '@sendgrid/mail',
        'better-sqlite3',
        'ioredis',
        'mysql2',
        'mysql2/promise',
        'nodemailer',
        'openai',
        'pg',
        'stripe',
        'twilio',
        '@aws-sdk/client-bedrock-runtime',
        'playwright',
        // Background queue peer deps — optional, only loaded when that adapter is used
        'bullmq',
        'kafkajs',
        'amqplib',
        '@aws-sdk/client-sqs',
    ],
});
